# Generated by Django 4.2.6 on 2023-11-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('SEQ_NO', models.IntegerField(primary_key=True, serialize=False)),
                ('ISBN_THIRTEEN_NO', models.CharField(blank=True, max_length=13)),
                ('VLM_NM', models.CharField(blank=True, max_length=20, null=True)),
                ('TITLE_NM', models.CharField(blank=True, max_length=1200, null=True)),
                ('AUTHR_NM', models.CharField(blank=True, max_length=1000, null=True)),
                ('PUBLISHER_NM', models.CharField(blank=True, max_length=1000, null=True)),
                ('PBLICTE_DE', models.CharField(blank=True, max_length=10, null=True)),
                ('ADTION_SMBL_NM', models.CharField(blank=True, max_length=5, null=True)),
                ('PRC_VALUE', models.CharField(blank=True, max_length=20, null=True)),
                ('IMAGE_URL', models.CharField(blank=True, max_length=1000, null=True)),
                ('BOOK_INTRCN_CN', models.TextField(blank=True, null=True)),
                ('KDC_NM', models.CharField(blank=True, max_length=20, null=True)),
                ('TITLE_SBST_NM', models.CharField(blank=True, max_length=1200, null=True)),
                ('AUTHR_SBST_NM', models.CharField(blank=True, max_length=1000, null=True)),
                ('TWO_PBLICTE_DE', models.CharField(blank=True, max_length=10, null=True)),
                ('INTNT_BOOKST_BOOK_EXST_AT', models.CharField(blank=True, max_length=1, null=True)),
                ('PORTAL_SITE_BOOK_EXST_AT', models.CharField(blank=True, max_length=1, null=True)),
                ('ISBN_NO', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
