# Generated by Django 4.2.6 on 2023-11-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-pk']},
        ),
    ]
