# Generated by Django 4.2.6 on 2023-12-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('olid', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('authors', models.CharField(blank=True, max_length=100, null=True)),
                ('authors_id', models.CharField(blank=True, max_length=100, null=True)),
                ('publishers', models.CharField(blank=True, max_length=100, null=True)),
                ('publish_places', models.CharField(blank=True, max_length=100, null=True)),
                ('languages', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_pages', models.IntegerField(blank=True, null=True)),
                ('physical_format', models.CharField(blank=True, max_length=100, null=True)),
                ('physical_dimensions', models.CharField(blank=True, max_length=100, null=True)),
                ('subjects', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('preview_url', models.CharField(blank=True, max_length=200, null=True)),
                ('info_url', models.CharField(blank=True, max_length=200, null=True)),
                ('img_url_s', models.CharField(blank=True, max_length=200, null=True)),
                ('img_url_m', models.CharField(blank=True, max_length=200, null=True)),
                ('img_url_l', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
