# Generated by Django 4.2.6 on 2023-12-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subjects',
            field=models.JSONField(default=dict, verbose_name='json'),
        ),
    ]
