# Generated by Django 4.2.6 on 2023-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_bestseller',
            },
        ),
    ]
