# Generated by Django 4.2.6 on 2023-12-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_publish_date_alter_book_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('isbn', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_newrelease',
            },
        ),
    ]
