# Generated by Django 4.2.6 on 2023-12-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_newrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authors_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=50, null=True)),
                ('birth_date', models.CharField(max_length=100, null=True)),
                ('death_date', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'authors',
            },
        ),
    ]
